apiVersion: apps/v1
kind: Deployment
metadata:
  name: training-web-app
spec:
  replicas: 1
  selector:
    matchLabels:
      app: training-web-app
  template:
    metadata:
      labels:
        app: training-web-app
    spec:
      containers:
      - name: training-web-app
        image: jmfede/web-app:v6
        ports:
        - containerPort: 80
---
apiVersion: v1
kind: Service
metadata:
  name: training-web-app-svc
spec:
  ports:
    - name: "http"
      port: 80
      targetPort: 80
  type: LoadBalancer  
  selector:
    app: training-web-app 
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: training-api
spec:
  replicas: 1
  selector:
    matchLabels:
      app: training-api
  template:
    metadata:
      labels:
        app: training-api
    spec:
      containers:
      - name: training-api
        image: jmfede/training-api:v1
        ports:
        - containerPort: 80
---
apiVersion: v1
kind: Service
metadata:
  name: training-api
spec:
  ports:
  - name: "11011"
    port: 11001
    targetPort: 80
  selector:
    app: training-api
---

apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: mysql-pv-claim
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 1Gi
---

apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: sql-database
spec:
  serviceName: sql-database
  replicas: 1
  selector:
    matchLabels:
      app: sql-database
  template:
    metadata:
      labels:
        app: sql-database
    spec:
      containers:
        - name: sql-database
          image: jmfede/sql-db:v1
          env:
            - name: SA_PASSWORD
              value: yourStrong(!)Password
            - name: ACCEPT_EULA
              value: "Y"
          ports:
            - containerPort: 1433
          volumeMounts:
            - name: mysql-persistent-storage
              mountPath: /var/lib/mysql
  volumeClaimTemplates:
    - metadata:
        name: mysql-persistent-storage
      spec:
        accessModes: [ "ReadWriteOnce" ]
        resources:
          requests:
            storage: 1Gi
---
apiVersion: v1
kind: Service
metadata:
  name: mysql
spec:
  selector:
    app: sql-database
  ports:
    - protocol: TCP
      port: 1433
      targetPort: 1433
