apiVersion: apps/v1
kind: Deployment
metadata:
  name: frontend
spec:
  replicas: 1
  selector:
    matchLabels:
      app: frontend
  template:
    metadata:
      labels:
        app: frontend
    spec:
      containers:
      - name: frontend
        image: jmfede/angular-app:v1
        ports:
        - containerPort: 4200
---
apiVersion: v1
kind: Service
metadata:
  name: frontend
spec:
  type: LoadBalancer  # Expose the service outside the cluster
  ports:
    - port: 80  # Port exposed by the service
      protocol: TCP
      targetPort: 4200  # Port your application listens on
  selector:
    app: frontend  # Label selector to match pods
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: backend
spec:
  replicas: 1
  selector:
    matchLabels:
      app: backend
  template:
    metadata:
      labels:
        app: backend
    spec:
      containers:
      - name: backend
        image: jmfede/dotnet-api:v1
        ports:
        - containerPort: 8080
---
apiVersion: v1
kind: Service
metadata:
  name: backend
spec:
  selector:
    app: backend
  ports:
  - protocol: TCP
    port: 8080
    targetPort: 8080
---
apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: mssql
spec:
  serviceName: mssql
  replicas: 1
  selector:
    matchLabels:
      app: mssql
  template:
    metadata:
      labels:
        app: mssql
    spec:
      containers:
      - name: mssql
        image: jmfede/sql-db:v1
        ports:
        - containerPort: 1433
        env:
        - name: ACCEPT_EULA
          value: "Y"
volumeClaimTemplates:
  - metadata:
    name: mssql
    spec:
    accessModes:
    - ReadWriteOnce
    resources:
      requests:
      storage: 8Gi



